const RobustUI=(()=>{
 'use strict';
 const storageKey='qpl-robust-v1',id=x=>document.getElementById(x);
 let send,ready=false,locked=false,seq=0,busy=false,options=Robust.defaults(),enabled=true;
 function persist(){try{localStorage.setItem(storageKey,JSON.stringify({enabled,options}));}catch{}}
 function controls(){id('robust-mode').value=enabled?'robust':'manual';id('robust-dd').value=options.maxDrawdown;id('robust-cvar').value=options.maxCvar;for(const name of ['robust-mode','robust-dd','robust-cvar'])id(name).disabled=locked;id('robust-run').disabled=locked||!ready||busy;id('robust-export').disabled=!state.robustReport||busy;id('robust-mode-note').textContent=enabled?'아래 경주 후보에 강건 전략을 적용합니다. 가중치 실험실은 별도 비교이며, 슬라이더를 움직여도 강건 전략은 바뀌지 않습니다.':'아래 경주 후보에 가중치 실험실의 설정을 적용합니다. 강건 검증 결과는 비교용으로 유지합니다.';}
 function clear(){state.robustReport=null;id('robust-results').innerHTML='';id('robust-live').textContent='계산 중';id('robust-export').disabled=true;selectors();}
 function calculate(){if(!ready||busy)return;busy=true;seq++;clear();controls();id('robust-status').textContent='108개 설정을 이전 기간에서 비교하고 다음 달을 평가하는 중…';id('robust-panel').setAttribute('aria-busy','true');send({type:'robust',id:seq,settings:options});}
 function render(report){
  state.robustReport=report;const r=report.result,b=report.baseline,latest=report.latest;
  id('robust-live').textContent=money(r.profit_krw,true);id('robust-live').className=colored(r.profit_krw);
  id('robust-status').textContent=`${report.from}–${report.through} · ${report.folds.length}개월 순차 평가 · ${r.bets}조합 × 10,000원 · 과거 재계산`;
  const metric=(label,value)=>`<div class="metric"><span>${label}</span><strong>${value}</strong></div>`;
  id('robust-results').innerHTML=`<div class="metrics">${metric('수익률 · ROI',pct(r.roi,2))}${metric('일별 최대낙폭',money(r.drawdown_krw))}${metric('주간 CVaR 80%',money(r.weekly_cvar_krw))}</div>${chart(r.curve,'강건 전략 월별 워크포워드 누적 세전 손익')}<p class="small">적용한 선택 한도: 최대낙폭 ${money(report.limits.maxDrawdown)}, 주간 CVaR ${money(report.limits.maxCvar)}.<br>총 베팅 ${money(r.stake_krw)} · ${r.weeks}개 경주 주간의 손실이 큰 20% 평균 · 미베팅 주간 포함. 월별 표의 마지막 달은 ${report.through}까지입니다.</p><p class="notice">${r.profit_krw>0?'과거 순차 평가에서 흑자입니다. 미래 수익이 검증된 것은 아닙니다.':'과거 순차 평가에서 수익 개선이 확인되지 않았습니다. 강건 전략도 손실이 발생할 수 있습니다.'} 위험 한도는 설정 선택 기간에 적용하며, 다음 달의 손실을 보장하거나 자동으로 중단하는 한도가 아닙니다.</p><details><summary>동일 기간의 기존 기본값과 비교</summary><div class="table-scroll"><table><thead><tr><th>항목</th><th>강건 전략</th><th>기존 기본값</th></tr></thead><tbody><tr><td>세전 손익</td><td>${money(r.profit_krw,true)}</td><td>${money(b.profit_krw,true)}</td></tr><tr><td>베팅 수</td><td>${r.bets}</td><td>${b.bets}</td></tr><tr><td>ROI</td><td>${pct(r.roi,2)}</td><td>${pct(b.roi,2)}</td></tr><tr><td>최대낙폭</td><td>${money(r.drawdown_krw)}</td><td>${money(b.drawdown_krw)}</td></tr><tr><td>주간 CVaR 80%</td><td>${money(r.weekly_cvar_krw)}</td><td>${money(b.weekly_cvar_krw)}</td></tr></tbody></table></div><p class="small">기존 기본값: 예상수익 가중치 100, 하한 10%, 경주당 1조합. 베팅 횟수 차이도 낙폭에 영향을 줍니다.</p></details><details><summary>월별 선택 설정·다음 달 실제 손익</summary>${report.folds.map(f=>`<details class="robust-fold"><summary>${f.month.slice(0,4)}.${f.month.slice(4)} · ${f.policy?'선택 '+f.result.bets+'조합':'선택 보류'} · ${money(f.result.profit_krw,true)}</summary><p>오차 보정: ${f.calibration.through}까지 ${f.calibration.months}개월<br>설정 선택: ${f.selection_from} 이상, ${f.selection_before} 미만<br>108개 중 조건 충족 ${f.feasible}개</p>${f.policy?`<p>보수적 기대수익률 하한 ${pct(f.policy.minEdge,0)} · 경주당 1조합<br>선택 기간 손익 ${money(f.selection.profit_krw,true)} · 최대낙폭 ${money(f.selection.drawdown_krw)} · 주간 CVaR ${money(f.selection.weekly_cvar_krw)}</p><p>${f.policy.weights.map((w,i)=>esc(Tuning.factors[i][1])+' '+w).join(' · ')}</p>`:'<p>양의 손익·20조합 이상·10개 경주 주간 이상·위험 한도를 모두 통과한 설정이 없어 베팅하지 않습니다.</p>'}<p>다음 달 평가: ${f.result.bets}조합 · ${money(f.result.profit_krw,true)} · ROI ${pct(f.result.roi,2)}${f.evaluation_limit_exceeded?' · 평가 기간 위험 한도 초과':''}</p></details>`).join('')}</details><p class="small">${esc(report.note)} 기본 예측모델은 고정하고, 오차 보정과 가중치·선택 하한을 시간순으로 검증합니다.</p>`;
  id('robust-current').textContent=latest?`${latest.month.slice(0,4)}.${latest.month.slice(4)} 적용 설정: ${latest.policy?latest.policy.id+' · 보수적 하한 '+pct(latest.policy.minEdge,0):'조건 충족 설정 없음 · 선택 보류'}`:'워크포워드에 필요한 기간이 부족합니다.';
  selectors();
 }
 function receive(m){if(!m.type.startsWith('robust-')||m.id!==seq)return; if(m.type==='robust-progress')id('robust-status').textContent=`${m.month.slice(0,4)}.${m.month.slice(4)} 평가 완료 · ${m.done}개월 계산 중…`;else if(m.type==='robust-result'){busy=false;id('robust-panel').setAttribute('aria-busy','false');render(m.report);controls();}else if(m.type==='robust-error'){busy=false;state.robustReport=null;id('robust-panel').setAttribute('aria-busy','false');id('robust-status').textContent=m.message;id('robust-live').textContent='계산 불가';controls();selectors();}}
 function init(post,isLocked){send=post;locked=isLocked;try{const saved=JSON.parse(localStorage.getItem(storageKey));if(saved){enabled=saved.enabled!==false;options=Robust.settings(saved.options);}else if(locked)enabled=false;}catch{}state.robustEnabled=enabled;controls();
  for(const name of ['robust-dd','robust-cvar'])id(name).addEventListener('input',()=>{if(locked){controls();return;}id('robust-status').textContent='입력한 한도는 ‘검증·추천 갱신’을 누르면 적용됩니다. 아래 결과는 이전에 적용한 한도 기준입니다.';});
  id('robust-mode').addEventListener('change',e=>{if(locked){controls();return;}enabled=e.target.value==='robust';state.robustEnabled=enabled;persist();controls();selectors();});
  id('robust-run').addEventListener('click',()=>{if(locked||busy)return;const fields=[id('robust-dd'),id('robust-cvar')];if(fields.some(el=>!el.reportValidity()))return;options=Robust.settings({maxDrawdown:+fields[0].value,maxCvar:+fields[1].value});persist();calculate();});
  id('robust-export').addEventListener('click',()=>{if(!state.robustReport||busy)return;const report=state.robustReport,rows=[['날짜','지역','경주','조합','원래기대수익률','보수적기대수익률','확정배당','세전손익','적용설정'],...report.ledger.map(b=>[b.date,b.venue,b.race_no,b.numbers.join('-'),b.edge,b.robust_edge,b.gross,b.profit_krw,b.policy_id])],blob=new Blob(['\ufeff'+rows.map(row=>row.join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='qpl-robust-walk-forward.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 }
 function onReady(){ready=true;calculate();}
 function reconnect(){ready=false;busy=false;seq++;clear();controls();id('robust-status').textContent='자료를 다시 불러오는 중…';}
 function fail(message){ready=false;busy=false;seq++;clear();id('robust-panel').setAttribute('aria-busy','false');id('robust-status').textContent=message+' 가중치 실험실의 자료 다시 불러오기를 눌러 주세요.';id('robust-live').textContent='계산 불가';controls();}
 function setLocked(value){locked=value;controls();}
 return {init,receive,onReady,reconnect,setLocked,fail};
})();
