const SensitivityUI=(()=>{
 const fields=[0,1,2,3,4,5,6,7,8,'edge'],curves=new Map();let getSettings,isLocked,apply;
 const target=f=>document.getElementById('sweep-'+f),current=f=>f==='edge'?Math.round(getSettings().minEdge*100):getSettings().weights[f];
 function clear(){curves.clear();for(const f of fields){target(f).innerHTML='<p class="small">0~100% 손익 곡선 계산 중…</p>';target(f).setAttribute('aria-busy','true');}}
 function fail(){curves.clear();for(const f of fields){target(f).innerHTML='<p class="small">손익 곡선을 계산하지 못했습니다. 자료를 다시 불러와 주세요.</p>';target(f).setAttribute('aria-busy','false');}}
 function draw(field){const curve=curves.get(field);if(!curve)return;const p=curve.points,v=current(field),now=p[v],peak=p.reduce((a,b)=>b.profit_krw>a.profit_krw?b:a),values=p.map(p=>p.profit_krw),low=Math.min(...values),high=Math.max(...values),pad=Math.max(1000,(high-low)*.08),lo=low-pad,hi=high+pad,x=n=>54+n/100*292,y=n=>122-(n-lo)/(hi-lo)*94,fmt=n=>(n/10000).toLocaleString('ko-KR',{maximumFractionDigits:1})+'만',name=field==='edge'?'모델 기대수익률 하한':Tuning.factors[field][1],disabled=isLocked();
 const ticks=[hi,(hi+lo)/2,lo],line=p.map(p=>`${x(p.value).toFixed(2)},${y(p.profit_krw).toFixed(2)}`).join(' ');
 target(field).setAttribute('aria-busy','false');target(field).innerHTML=`<p class="sweep-caption">조정 후 누적손익 (만원)</p><svg class="sweep-chart" viewBox="0 0 360 153" role="slider" tabindex="${disabled?-1:0}" aria-label="${esc(name)} 손익 곡선으로 값 조절" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${Math.max(0,v)}" aria-valuetext="${v}%${now?' · '+money(now.profit_krw,true):' · 그래프 범위 밖'}" aria-disabled="${disabled}" data-current="${v}">${ticks.map(n=>`<line x1="54" y1="${y(n)}" x2="346" y2="${y(n)}" class="sweep-grid"/><text x="48" y="${y(n)+4}" text-anchor="end">${fmt(n)}</text>`).join('')}${lo<=0&&hi>=0?`<line x1="54" y1="${y(0)}" x2="346" y2="${y(0)}" class="sweep-zero"/>`:''}<polyline points="${line}" class="sweep-line"/>${now?`<line x1="${x(v)}" y1="28" x2="${x(v)}" y2="122" class="sweep-current"/><circle cx="${x(v)}" cy="${y(now.profit_krw)}" r="4" class="sweep-dot"/>`:''}${[0,50,100].map(n=>`<text x="${x(n)}" y="145" text-anchor="${n===100?'end':n===0?'start':'middle'}">${n}%</text>`).join('')}</svg><p class="sweep-readout">현재 ${v}% · ${now?money(now.profit_krw,true)+' · '+now.bets+'조합':'그래프 범위 밖'}<br>이 곡선 최고 ${peak.value}% · ${money(peak.profit_krw,true)}</p>`;
 const svg=target(field).querySelector('svg');svg.addEventListener('click',event=>{if(isLocked())return;const rect=svg.getBoundingClientRect(),point=(event.clientX-rect.left)/rect.width*360;apply(field,Math.max(0,Math.min(100,Math.round((point-54)/292*100))));});svg.addEventListener('keydown',event=>{if(isLocked())return;let next;if(event.key==='Home')next=0;else if(event.key==='End')next=100;else if(['ArrowLeft','ArrowDown'].includes(event.key))next=v-1;else if(['ArrowRight','ArrowUp'].includes(event.key))next=v+1;else return;event.preventDefault();apply(field,Math.max(0,Math.min(100,next)));});
 }
 function receive(curve){if(!fields.includes(curve.field)||curve.points.length!==101)return;curves.set(curve.field,curve);draw(curve.field);}
 function lock(){for(const f of fields)draw(f);}
 function init(read,locked,change){getSettings=read;isLocked=locked;apply=change;clear();}
 return {init,clear,receive,lock,fail};
})();
