const Tuner=(()=>{
let worker,ready=false,timer,seq=0,initialized=false,last=null,locked=false,presets=[],builtins=[];
const id=x=>document.getElementById(x),key='qpl-tuning-v1';
function save(){try{localStorage.setItem(key,JSON.stringify(state.tuning));}catch{}}
function labels(){const sum=state.tuning.weights.reduce((a,b)=>a+b,0);Tuning.factors.forEach((f,i)=>{id(`weight-${i}`).value=state.tuning.weights[i];id(`weight-out-${i}`).textContent=`${state.tuning.weights[i]} · 비중 ${sum?(state.tuning.weights[i]/sum*100).toFixed(0):0}%`;});id('tune-edge-value').textContent=`${Math.round(state.tuning.minEdge*100)}%`;id('tune-edge').value=Math.round(state.tuning.minEdge*100);id('tune-count').value=state.tuning.maxPerRace;id('tune-period').value=state.tuning.period;id('tune-venue').value=state.tuning.venue;}
function message(s){id('preset-status').textContent=s;}
function lockControls(){if(typeof SensitivityUI!=='undefined')SensitivityUI.lock();if(typeof RobustUI!=='undefined')RobustUI.setLocked(locked);for(const el of id('tune-controls').querySelectorAll('input'))el.disabled=locked;for(const name of ['tune-edge','tune-count','tune-period','tune-venue','tune-reset','preset-load'])id(name).disabled=locked;id('tune-lock').textContent=locked?'잠금 해제':'가중치 잠금';id('tune-lock').setAttribute('aria-pressed',String(locked));id('tune-lock-note').textContent=locked?'잠김 · 가중치와 선택 조건을 변경할 수 없습니다.':'가중치와 선택 조건을 변경할 수 있습니다.';}
function drawPresets(selected){const select=id('preset-list');select.replaceChildren();const option=(value,name)=>{const o=document.createElement('option');o.value=value;o.textContent=name;select.append(o);};option('','저장된 조합 선택');for(const p of builtins)option('builtin-'+p.id,p.name);for(const p of presets)option(p.id,p.name);if(selected)select.value=selected;id('preset-delete').disabled=!presets.some(p=>p.id===select.value);}
function putPresets(next,selected){try{PresetStore.write(localStorage,next);presets=next;drawPresets(selected);return true;}catch(e){message('저장하지 못했습니다. 저장 공간·브라우저 설정을 확인해 주세요.');return false;}}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function initPresets(){try{locked=localStorage.getItem(PresetStore.lockKey)==='true';}catch{}try{presets=PresetStore.read(localStorage);}catch{message('저장 조합을 읽지 못했습니다. 백업 파일로 복원할 수 있습니다.');}drawPresets();lockControls();
 id('tune-lock').addEventListener('click',()=>{locked=!locked;try{localStorage.setItem(PresetStore.lockKey,String(locked));message(locked?'현재 설정을 잠갔습니다.':'잠금을 해제했습니다.');}catch{message('이번 화면에서는 적용했지만 잠금 상태를 저장하지 못했습니다.');}lockControls();});
 id('preset-save').addEventListener('click',()=>{const name=id('preset-name').value.trim().slice(0,40);if(!name){message('저장할 이름을 입력해 주세요.');id('preset-name').focus();return;}if(presets.some(p=>p.name===name)){message('같은 이름이 있습니다. 다른 이름으로 저장해 주세요.');return;}if(presets.length>=30){message('최대 30개까지 저장할 수 있습니다.');return;}const p={id:'p'+crypto.randomUUID(),name,settings:JSON.parse(JSON.stringify(state.tuning))};if(putPresets([...presets,p],p.id)){id('preset-name').value='';message(`「${name}」 저장 완료 · 이 브라우저에 보관됩니다.`);}});
 id('preset-list').addEventListener('change',()=>{id('preset-delete').disabled=!presets.some(p=>p.id===id('preset-list').value);});
 id('preset-load').addEventListener('click',()=>{if(locked)return;const value=id('preset-list').value,p=value.startsWith('builtin-')?builtins.find(p=>'builtin-'+p.id===value):presets.find(p=>p.id===value);if(!p)return;state.tuning=Tuning.settings(p.settings);changed();message(`「${p.name}」 적용 완료`);});
 id('preset-delete').addEventListener('click',()=>{const p=presets.find(p=>p.id===id('preset-list').value);if(p&&putPresets(presets.filter(x=>x.id!==p.id)))message(`「${p.name}」 저장 목록에서 삭제했습니다. 현재 가중치는 유지합니다.`);});
 id('preset-export').addEventListener('click',()=>{download(new Blob([PresetStore.encode(presets)],{type:'application/json'}),'qpl-weight-presets.json');});
 id('preset-import').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>100000)throw Error('파일이 너무 큽니다.');const added=PresetStore.validate(JSON.parse(await f.text())),next=[...presets];for(const p of added){if(next.some(x=>x.id===p.id&&JSON.stringify(x)===JSON.stringify(p)))continue;const name=next.some(x=>x.name===p.name)?(p.name.slice(0,28)+' (가져옴 '+(next.length+1)+')'):p.name;next.push({...p,id:'p'+crypto.randomUUID(),name});}if(next.length>30)throw Error('가져오면 30개를 초과합니다.');if(putPresets(next))message('백업 조합을 가져왔습니다. 적용하려면 목록에서 불러오기를 누르세요.');}catch(e){message('가져오기 실패: '+e.message);}finally{e.target.value='';}});
 fetch('data/weight-recommendations.json?v=stake-10000-v1',{cache:'no-cache'}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(doc=>{if(doc.unit_stake_krw!==Tuning.STAKE)throw Error('베팅 단위가 다른 비교 자료');builtins=doc.presets.filter(p=>PresetStore.validSettings(p.settings));drawPresets(id('preset-list').value);id('weight-search-note').textContent=doc.note;id('weight-search-results').innerHTML='<div class="table-scroll"><table><thead><tr><th>조합</th><th>2025 순손익</th><th>2026 순손익</th><th>2026 최대 낙폭</th></tr></thead><tbody>'+doc.presets.map(p=>`<tr><td>${esc(p.name)}</td><td>${money(p.results.y2025.profit_krw,true)}</td><td>${money(p.results.y2026.profit_krw,true)}</td><td>${money(p.results.y2026.drawdown_krw)}</td></tr>`).join('')+'</tbody></table></div>';}).catch(()=>{id('weight-search-note').textContent='탐색 결과를 불러오지 못했습니다. 저장 조합 기능은 계속 사용할 수 있습니다.';});
}

function changed(){labels();save();selectors();schedule();}
function schedule(){last=null;SensitivityUI.clear();id('tune-metrics').innerHTML='';id('tune-chart').innerHTML='';id('tune-months').innerHTML='';id('tune-dd').textContent='';id('tune-live-profit').textContent='계산 중…';id('tune-live-roi').textContent='';seq++;clearTimeout(timer);id('tune-status').textContent=ready?'새 가중치로 전체 조합을 다시 선택·정산하는 중…':'과거 전체 조합 자료를 불러오는 중…';id('tune-results').setAttribute('aria-busy','true');id('tune-download').disabled=true;if(ready)timer=setTimeout(()=>worker.postMessage({type:'calculate',id:seq,settings:state.tuning}),150);}
function render(result,baseline){last=result;const r=result;id('tune-live-profit').textContent=money(r.profit_krw,true);id('tune-live-profit').className=colored(r.profit_krw);id('tune-live-roi').textContent=pct(r.roi,2);id('tune-results').setAttribute('aria-busy','false');id('tune-status').textContent=`${r.bets.toLocaleString()}조합 × 10,000원 · 총 베팅 ${money(r.stake_krw)} · 적중률 ${pct(r.hit_rate)} · 과거 재계산`;
id('tune-metrics').innerHTML=`<div class="metric"><span>조정 후 누적 세전 손익</span><strong class="${colored(r.profit_krw)}">${money(r.profit_krw,true)}</strong></div><div class="metric"><span>수익률 · ROI</span><strong class="${colored(r.roi)}">${pct(r.roi,2)}</strong></div><div class="metric"><span>기본 설정 대비 손익</span><strong class="${colored(r.profit_krw-baseline)}">${money(r.profit_krw-baseline,true)}</strong></div>`;
id('tune-chart').innerHTML=chart(r.curve,'사용자 가중치 시뮬레이션 누적 세전 손익');id('tune-dd').textContent=`일별 최대 낙폭 ${money(r.drawdown_krw)} · 같은 기간·지역의 기본값과 비교합니다.`;
id('tune-months').innerHTML=`<div class="table-scroll"><table><thead><tr><th>월</th><th>선택 수</th><th>순손익</th></tr></thead><tbody>${r.months.map(m=>`<tr><td>${m.month}</td><td>${m.bets}</td><td>${money(m.profit_krw,true)}</td></tr>`).join('')}</tbody></table></div><p>${r.byVenue.map(v=>`${venues[v.venue]} ${money(v.profit_krw,true)}`).join(' · ')||'선택된 조합 없음'}</p>`;id('tune-download').disabled=false;}
function connect(){ready=false;if(typeof RobustUI!=='undefined')RobustUI.reconnect();if(worker)worker.terminate();try{worker=new Worker('tuning-worker.js?v=sweep-v1');worker.onmessage=({data:m})=>{if(m.type==='sensitivity'){if(m.id===seq&&JSON.stringify(m.settings)===JSON.stringify(state.tuning))SensitivityUI.receive(m.curve);return;}if(m.type.startsWith('robust-')){RobustUI.receive(m);return;}if(m.type==='ready'){ready=true;id('tune-coverage').textContent=`2025.04.01–2026.09.10 · ${m.races.toLocaleString()}경주 · ${m.candidates.toLocaleString()}개 전체 조합`;schedule();RobustUI.onReady();}else if(m.type==='result'&&m.id===seq&&JSON.stringify(m.settings)===JSON.stringify(state.tuning))render(m.result,m.baseline);else if(m.type==='error'&&(m.id===undefined||m.id===seq)){SensitivityUI.fail();if(m.id===undefined)RobustUI.fail(m.message);id('tune-status').textContent=m.message;id('tune-live-profit').textContent='계산 불가';id('tune-live-roi').textContent='';id('tune-metrics').innerHTML='';id('tune-chart').innerHTML='';id('tune-results').setAttribute('aria-busy','false');}};worker.onerror=()=>{SensitivityUI.fail();RobustUI.fail('계산 작업이 중단되었습니다.');id('tune-status').textContent='시뮬레이션 계산을 시작하지 못했습니다. 자료 다시 불러오기를 눌러 주세요.';};worker.postMessage({type:'load'});}catch{ id('tune-status').textContent='이 브라우저에서 시뮬레이션을 시작할 수 없습니다.';}}
function init(){if(initialized)return;initialized=true;let saved;try{saved=JSON.parse(localStorage.getItem(key));}catch{}state.tuning=Tuning.settings(saved);
id('tune-controls').innerHTML=Tuning.factors.map((f,i)=>`<div class="weight-control"><div><label for="weight-${i}">${f[1]}</label><output id="weight-out-${i}" for="weight-${i}"></output></div><input id="weight-${i}" type="range" min="0" max="100" step="1" aria-describedby="weight-help-${i}"><p id="weight-help-${i}">${f[2]}</p><div id="sweep-${i}" class="sensitivity" aria-busy="true"></div></div>`).join('');Tuning.factors.forEach((_,i)=>id(`weight-${i}`).addEventListener('input',e=>{if(locked){labels();return;}state.tuning.weights[i]=+e.target.value;changed();}));
for(const [element,field] of [['tune-edge','minEdge'],['tune-count','maxPerRace'],['tune-period','period'],['tune-venue','venue']])id(element).addEventListener(element==='tune-edge'?'input':'change',e=>{if(locked){labels();return;}state.tuning[field]=field==='minEdge'?+e.target.value/100:field==='maxPerRace'?+e.target.value:e.target.value;changed();});
id('tune-reset').addEventListener('click',()=>{if(locked)return;state.tuning=Tuning.defaults();changed();});id('tune-retry').addEventListener('click',connect);
id('tune-download').addEventListener('click',()=>{if(!last)return;const rows=[['날짜','지역','경주','조합','확정배당','순손익'],...last.ledger.map(b=>[b.date,venues[b.venue],b.race_no,b.numbers.join('-'),b.gross,b.profit_krw])];const blob=new Blob(['\ufeff'+rows.map(r=>r.join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='qpl-simulation.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});SensitivityUI.init(()=>state.tuning,()=>locked,(field,value)=>{if(locked)return;if(field==='edge')state.tuning.minEdge=value/100;else state.tuning.weights[field]=value;changed();});labels();initPresets();RobustUI.init(m=>worker.postMessage(m),locked);connect();}
return {init};
})();
