const Tuner=(()=>{
let worker,ready=false,timer,seq=0,initialized=false,last=null;
const id=x=>document.getElementById(x),key='qpl-tuning-v1';
function save(){try{localStorage.setItem(key,JSON.stringify(state.tuning));}catch{}}
function labels(){const sum=state.tuning.weights.reduce((a,b)=>a+b,0);Tuning.factors.forEach((f,i)=>{id(`weight-${i}`).value=state.tuning.weights[i];id(`weight-out-${i}`).textContent=`${state.tuning.weights[i]} · 비중 ${sum?(state.tuning.weights[i]/sum*100).toFixed(0):0}%`;});id('tune-edge-value').textContent=`${Math.round(state.tuning.minEdge*100)}%`;id('tune-edge').value=Math.round(state.tuning.minEdge*100);id('tune-count').value=state.tuning.maxPerRace;id('tune-period').value=state.tuning.period;id('tune-venue').value=state.tuning.venue;}
function changed(){labels();save();selectors();schedule();}
function schedule(){seq++;clearTimeout(timer);id('tune-status').textContent=ready?'새 가중치로 전체 조합을 다시 선택·정산하는 중…':'과거 전체 조합 자료를 불러오는 중…';id('tune-results').setAttribute('aria-busy','true');id('tune-download').disabled=true;if(ready)timer=setTimeout(()=>worker.postMessage({type:'calculate',id:seq,settings:state.tuning}),150);}
function render(result,baseline){last=result;const r=result;id('tune-results').setAttribute('aria-busy','false');id('tune-status').textContent=`${r.bets.toLocaleString()}조합 × 1,000원 · 총 베팅 ${money(r.stake_krw)} · 적중률 ${pct(r.hit_rate)} · 과거 재계산`;
id('tune-metrics').innerHTML=`<div class="metric"><span>조정 후 누적 세전 손익</span><strong class="${colored(r.profit_krw)}">${money(r.profit_krw,true)}</strong></div><div class="metric"><span>수익률 · ROI</span><strong class="${colored(r.roi)}">${pct(r.roi,2)}</strong></div><div class="metric"><span>기본 설정 대비 손익</span><strong class="${colored(r.profit_krw-baseline)}">${money(r.profit_krw-baseline,true)}</strong></div>`;
id('tune-chart').innerHTML=chart(r.curve,'사용자 가중치 시뮬레이션 누적 세전 손익');id('tune-dd').textContent=`일별 최대 낙폭 ${money(r.drawdown_krw)} · 같은 기간·지역의 기본값과 비교합니다.`;
id('tune-months').innerHTML=`<div class="table-scroll"><table><thead><tr><th>월</th><th>선택 수</th><th>순손익</th></tr></thead><tbody>${r.months.map(m=>`<tr><td>${m.month}</td><td>${m.bets}</td><td>${money(m.profit_krw,true)}</td></tr>`).join('')}</tbody></table></div><p>${r.byVenue.map(v=>`${venues[v.venue]} ${money(v.profit_krw,true)}`).join(' · ')||'선택된 조합 없음'}</p>`;id('tune-download').disabled=false;}
function connect(){ready=false;if(worker)worker.terminate();try{worker=new Worker('tuning-worker.js');worker.onmessage=({data:m})=>{if(m.type==='ready'){ready=true;id('tune-coverage').textContent=`2025.04.01–2026.09.10 · ${m.races.toLocaleString()}경주 · ${m.candidates.toLocaleString()}개 전체 조합`;schedule();}else if(m.type==='result'&&m.id===seq)render(m.result,m.baseline);else if(m.type==='error'&&(m.id===undefined||m.id===seq)){id('tune-status').textContent=m.message;id('tune-results').setAttribute('aria-busy','false');}};worker.onerror=()=>{id('tune-status').textContent='시뮬레이션 계산을 시작하지 못했습니다. 자료 다시 불러오기를 눌러 주세요.';};worker.postMessage({type:'load'});}catch{ id('tune-status').textContent='이 브라우저에서 시뮬레이션을 시작할 수 없습니다.';}}
function init(){if(initialized)return;initialized=true;let saved;try{saved=JSON.parse(localStorage.getItem(key));}catch{}state.tuning=Tuning.settings(saved);
id('tune-controls').innerHTML=Tuning.factors.map((f,i)=>`<div class="weight-control"><div><label for="weight-${i}">${f[1]}</label><output id="weight-out-${i}" for="weight-${i}"></output></div><input id="weight-${i}" type="range" min="0" max="100" step="5" aria-describedby="weight-help-${i}"><p id="weight-help-${i}">${f[2]}</p></div>`).join('');Tuning.factors.forEach((_,i)=>id(`weight-${i}`).addEventListener('input',e=>{state.tuning.weights[i]=+e.target.value;changed();}));
for(const [element,field] of [['tune-edge','minEdge'],['tune-count','maxPerRace'],['tune-period','period'],['tune-venue','venue']])id(element).addEventListener(element==='tune-edge'?'input':'change',e=>{state.tuning[field]=field==='minEdge'?+e.target.value/100:field==='maxPerRace'?+e.target.value:e.target.value;changed();});
id('tune-reset').addEventListener('click',()=>{state.tuning=Tuning.defaults();changed();});id('tune-retry').addEventListener('click',connect);
id('tune-download').addEventListener('click',()=>{if(!last)return;const rows=[['날짜','지역','경주','조합','확정배당','순손익'],...last.ledger.map(b=>[b.date,venues[b.venue],b.race_no,b.numbers.join('-'),b.gross,b.profit_krw])];const blob=new Blob(['\ufeff'+rows.map(r=>r.join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='qpl-simulation.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});labels();connect();}
return {init};
})();
