(function(root){'use strict';
const factors=[['ev','예상수익','모델 확률 × 예상 배당 − 1'],['prob','적중확률','모델 추정 복연승 적중확률'],['dividend','예상배당','실시간 시세가 아닌 모델 예상 배당'],['form','최근 성적','두 말의 최근 성적 평균'],['rating','능력·레이팅','두 말의 상대 레이팅 평균'],['jockey','기수','두 기수의 과거 실제 연승률 평균'],['trainer','조교사','두 조교사의 과거 실제 연승률 평균'],['distance','거리 적성','두 말의 유사 거리 성적 평균'],['finish','종반 경쟁력','두 말의 상대 종반 속도 평균']];
const defaults=()=>({weights:[100,0,0,0,0,0,0,0,0],minEdge:.1,maxPerRace:1,period:'2026',venue:'all'});
function settings(x){const d=defaults();if(!x||!Array.isArray(x.weights)||x.weights.length!==9)return d;return {weights:x.weights.map(v=>Number.isFinite(+v)?Math.max(0,Math.min(100,Math.round(+v))):0),minEdge:Number.isFinite(+x.minEdge)?Math.max(-.5,Math.min(1,+x.minEdge)):d.minEdge,maxPerRace:[1,2,3].includes(+x.maxPerRace)?+x.maxPerRace:1,period:['2025','2026','all'].includes(x.period)?x.period:'2026',venue:['all','seoul','busan','jeju'].includes(x.venue)?x.venue:'all'};}
function normalized(raw){const bounds=raw[0]?.map((_,k)=>{const a=raw.map(r=>r[k]);return [Math.min(...a),Math.max(...a)];})||[];return raw.map(row=>row.map((v,k)=>{const [lo,hi]=bounds[k];return hi>lo?Math.round((v-lo)/(hi-lo)*10000)/10000:.5;}));}
function decorate(cs,hs){const map=new Map(hs.map(h=>[h.number,h.features_v7]));const ns=normalized(cs.map(c=>{const a=map.get(c.numbers[0]),b=map.get(c.numbers[1]);return [c.edge,c.prob,c.dividend,...[4,3,34,35,36,44].map(i=>(a[i]+b[i])/2)];}));return cs.map((c,i)=>({...c,factors:ns[i]}));}
function score(f,w){const n=w.reduce((s,v)=>s+v,0);return n?100*f.reduce((s,v,i)=>s+v*w[i],0)/n:0;}
function rank(cs,s){return cs.map(c=>({...c,tuningScore:score(c.factors,s.weights)})).sort((a,b)=>b.tuningScore-a.tuningScore||b.edge-a.edge||a.numbers[0]-b.numbers[0]||a.numbers[1]-b.numbers[1]);}
function select(cs,s){return s.weights.some(w=>w>0)?rank(cs,s).filter(c=>c.edge>=s.minEdge).slice(0,s.maxPerRace):[];}
function backtest(data,s){s=settings(s);let bets=0,hits=0,net=0,peak=0,dd=0;const days=new Map(),months=new Map(),venues=new Map(),ledger=[];
for(const r of data.races){if((s.period!=='all'&&!r.date.startsWith(s.period))||(s.venue!=='all'&&r.venue!==s.venue))continue;
const cs=r.rows.map(row=>({numbers:row.slice(0,2),edge:row[2],gross:row[3],factors:row.slice(4)}));
for(const c of select(cs,s)){const profit=c.gross-1;bets++;hits+=+(c.gross>0);net+=profit;days.set(r.date,(days.get(r.date)||0)+profit);for(const [m,k] of [[months,r.date.slice(0,6)],[venues,r.venue]]){const v=m.get(k)||{bets:0,net:0};v.bets++;v.net+=profit;m.set(k,v);}ledger.push({date:r.date,venue:r.venue,race_no:r.race_no,numbers:c.numbers,gross:c.gross,profit_krw:Math.round(profit*1000)});}}
let equity=0;const curve=[...days].sort(([a],[b])=>a.localeCompare(b)).map(([date,n])=>{equity+=n;peak=Math.max(peak,equity);dd=Math.max(dd,peak-equity);return {date,profit_units:equity};});
return {bets,hits,profit_krw:Math.round(net*1000),stake_krw:bets*1000,roi:bets?net/bets:null,hit_rate:bets?hits/bets:null,drawdown_krw:Math.round(dd*1000),curve,months:[...months].sort(([a],[b])=>a.localeCompare(b)).map(([month,v])=>({month,bets:v.bets,profit_krw:Math.round(v.net*1000)})),byVenue:[...venues].map(([venue,v])=>({venue,bets:v.bets,profit_krw:Math.round(v.net*1000)})),ledger};}
const api={factors,defaults,settings,normalized,decorate,score,rank,select,backtest};if(typeof module!=='undefined')module.exports=api;else root.Tuning=api;
})(globalThis);
