const fs=require('node:fs'),z=require('node:zlib'),T=require('../tuning.js');
const search=JSON.parse(fs.readFileSync('data/weight-search.json')),data=JSON.parse(z.gunzipSync(fs.readFileSync('data/tuning.json.gz')));
function summarize(s){const r=T.backtest(data,s),days=new Map();for(const b of r.ledger)days.set(b.date,(days.get(b.date)||0)+b.profit_krw);const returns=r.ledger.map(b=>b.gross*T.STAKE).sort((a,b)=>b-a);return {bets:r.bets,profit_krw:r.profit_krw,roi:r.roi,hit_rate:r.hit_rate,drawdown_krw:r.drawdown_krw,positive_months:r.months.filter(m=>m.profit_krw>0).length,months:r.months,byVenue:r.byVenue,without_best_day_profit_krw:r.profit_krw-Math.max(0,...days.values()),without_top5_returns_profit_krw:Math.round(r.profit_krw-returns.slice(0,5).reduce((a,b)=>a+b,0)),payout_stress_10pct_profit_krw:Math.round(r.ledger.reduce((s,b)=>s+(.9*b.gross-1)*T.STAKE,0))};}
const candidates=search.options.filter(o=>o.net_units[0]>=search.user_net_units[0]-1e-8&&o.net_units[1]>search.user_net_units[1]+1e-8).sort((a,b)=>b.net_units[1]-a.net_units[1]||b.net_units[0]-a.net_units[0]);
const rows=[['reference','첨부 원본',search.user_weights],['recent','2026 수익 상위 · 사후 탐색',search.best.recent.weights],['total','두 기간 합산 상위 · 사후 탐색',search.best.total.weights],['improved','첨부 대비 두 기간 개선 · 사후 탐색',candidates[0].weights]];
const presets=rows.map(([id,name,weights])=>{const settings={...T.defaults(),weights},results={};for(const [key,period] of [['y2025','2025'],['y2026','2026'],['all','all']])results[key]=summarize({...settings,period});return {id,name,settings,results};});
const note=`가중치 ${search.searched.toLocaleString()}개를 탐색했습니다. EV 하한 10%·경주당 1조합·10,000원 고정. 2025·2026 결과를 확인하며 찾은 사후 탐색 후보이므로 미래 흑자나 독립 검증을 뜻하지 않습니다. 첨부 화면의 숫자 가중치로 재계산했으며 평가 범위는 2026년·전체 지역을 기준으로 저장했습니다.`;
const out={schema:1,unit_stake_krw:T.STAKE,source_sha256:search.source_sha256,searched:search.searched,seed:search.seed,note,presets};fs.writeFileSync('data/weight-recommendations.json',JSON.stringify(out));const {options,...summary}=search;fs.writeFileSync('data/weight-search-summary.json',JSON.stringify(summary));
console.log(JSON.stringify(presets.map(p=>({id:p.id,weights:p.settings.weights,y2025:p.results.y2025,y2026:p.results.y2026,all:p.results.all.profit_krw})),null,2));
